# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZyProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZyProject
  pod 'MJExtension'
  pod 'BRPickerView'
  

end
