# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZyProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZyProject
  pod 'MJExtension'
  pod 'BRPickerView'
  pod 'FSCalendar'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'Masonry'
  pod 'MJRefresh', '~> 3.2.0'
  pod 'SDWebImage', '~> 5.0.6'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'Alamofire','<=4.9.1'
end
